project:
  type: website
  pre-render:
    - site-attachments/packages.R
    - site-attachments/purl-r-scripts.R
 # post-render: 
   # - site-attachments/docx2pdf.R
    # - site-attachments/create-example-folder.R
  render: 
    - "*.qmd"
    - "!recipe-card.qmd"
    - "!site-attachments/quarto-template.qmd"
  # resources:
  #   - CNAME
    
website:
  title: "Capaldi Recipe Box"
  site-url: "https://capaldi.info/recipebox"
  description: ""
  image: "apple-touch-icon.png"
  favicon: "apple-touch-icon.png"
  twitter-card: true
  open-graph: true
  navbar: false
  sidebar:
    style: "docked"
    search: true
    contents:
      - index.qmd
      - section: "Bread"
        contents: "bread/*"
    collapse-level: 1

  page-footer:
    right: 
      - text: "Built with Quarto"
        href: https://quarto.org/docs/websites
      - icon: github
        aria-label: Website Code Available Here
        href: https://github.com/ttalVlatt/recipebox
    left:
      - text: "M.J. Capaldi"
        href: https://capaldi.info

      
format:
  html:
    theme: lux
    css: site-attachments/styles.css
    toc: false
    email-obfuscation: references
    anchor-sections: false

editor: source

