project:
  type: website
  render: 
    - "*.qmd"
    - "!recipe-card.qmd"
    - "!site-attachments/quarto-template.qmd"
  # resources:
  #   - CNAME
    
website:
  title: "Capaldi's Recipe Box"
  site-url: "https://capaldi.info/recipebox"
  description: ""
  image: "apple-touch-icon.png"
  favicon: "apple-touch-icon.png"
  twitter-card: true
  open-graph: true
  sidebar:
    title: false
    subtitle: "From Picinisco"
    style: "docked"
    search: true
    contents:
      - section: "Sourdough"
        contents: "sourdough/*"
      - section: "Italian"
        contents: "italian/*"
    collapse-level: 1

      
format:
  html:
    theme: sketchy
    css: styles.css
    mainfont: Bradley Hand
    fontsize: 20pt
    email-obfuscation: references
    anchor-sections: false

editor: source

